services:
  app:
    image: todo-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - /usr/src/app/node_modules 
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    container_name: todo-frontend-dev # This will name the container hello-front-dev

  debug-helper:    
    image: busybox # docker compose  -f docker-compose.dev.yml run debug-helper wget -O - http://app:5173